name: just_audio_media_kit
description: package:media_kit bindings for just_audio
version: 1.0.0
repository: https://github.com/Pato05/just_audio_media_kit

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  just_audio_platform_interface: ^4.2.1
  media_kit: ^1.1.9
  media_kit_libs_windows_audio: ^1.0.9
  media_kit_libs_linux: ^1.1.3
  media_kit_native_event_loop: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
# Support both Windows and Linux
flutter:
  plugin:
    implements: just_audio_platform_interface
    platforms:
      windows:
        dartPluginClass: JustAudioMediaKit
        fileName: just_audio_media_kit.dart
      linux:
        dartPluginClass: JustAudioMediaKit
        fileName: just_audio_media_kit.dart
